### ISSUE TITLE
Split wasm part into a -sys version of this crate

### ISSUE THREAD

**Issue by oli-obk** [optozorax/quad-storage#1]
I was just considering implementing something like this when I remembered to search crates.io first. Thanks for implementing this!

Would you be ok with me splitting out the wasm part into a crate that just exposes free functions hiding the raw wasm opts and making quad-storage use that new crate on wasm?

**Comment by optozorax** [comment]
Hm, why do you need this? If you need this for quad ecosystem, it's better to add features to this crate. If you need it for your projects, it maybe better to use `web-sys` from `wasm-bindgen` which is already have [`local_storage`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Window.html#method.local_storage) function.

**Comment by oli-obk** [comment]
My use case is that I would like to use an entirely different file storage system on non-wasm (and not use lazy_static either), but I also don't want to duplicate what you did here for wasm.

I am using it for the quad ecosystem indeed.

My plans for non-wasm are:

* use the `directories` crate to find the appropriate project directory for save files
* instead of using a single save file and serialize a map, create one file per key, and use a directory structure to store keys. On wasm that directory structure would not exist, instead the paths would get serialized as strings, so you get keys like "player/x" and "player/y"

My generic plans for all areas are to make all the save/load operations generic over `Display` and `FromStr` for more convenience.

**Comment by optozorax** [comment]
Go ahead, I will accept PR with `-sys` crate.

**Comment by optozorax** [comment]
Done, [quad-storage-sys 0.1.0](https://crates.io/crates/quad-storage-sys) and [quad-storage 0.1.3](https://crates.io/crates/quad-storage) are published!
